[package]
name = "memory_manager"
version = "0.1.0"
edition = "2021"
description = "Garbage collector and heap management"

[dependencies]
core_types = { path = "../core_types" }
crossbeam = "0.8"
crossbeam-deque = "0.8"
crossbeam-epoch = "0.9"

[dev-dependencies]
