[package]
name = "bytecode_system"
version.workspace = true
edition.workspace = true

[dependencies]

[dev-dependencies]

[[test]]
name = "unit_tests"
path = "tests/unit/mod.rs"

[[test]]
name = "contracts_tests"
path = "tests/contracts/mod.rs"
