[package]
name = "builtins"
version.workspace = true
edition.workspace = true

[dependencies]
regex = "1.10"
serde_json = "1.0"
chrono = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"

[dev-dependencies]
