[package]
name = "jit_compiler"
version.workspace = true
edition.workspace = true

[dependencies]
bytecode_system = { path = "../bytecode_system" }
interpreter = { path = "../interpreter" }
core_types = { path = "../core_types" }

[dev-dependencies]
