[package]
name = "async_runtime"
version.workspace = true
edition.workspace = true

[dependencies]
core_types = { path = "../core_types" }

[dev-dependencies]

[[test]]
name = "unit_tests"
path = "tests/unit/mod.rs"

[[test]]
name = "contract_tests"
path = "tests/contracts/mod.rs"
